image: node:10

cache:
  paths:
    - aspire-floor-allocation/node_modules

stages:
  - deploy

before_script:
  - cd spire-floor-allocation
  - rm -rf build
  - CI=false npm install

pages:
  stage: deploy
  environment: Production
  script:
    - CI=false npm run build
    - cp build/index.html build/404.html
    - cp -r build/* ../../public/

  artifacts:
    paths:
      - public
  only:
    refs:
      - master